kind: ConfigMap
apiVersion: v1
metadata:
  name: mailserver.config
  labels:
    app: mailserver
data:
  postfix-accounts.cf: |
    user1@example.com| <password>

  postfix-virtual.cf: |
    alias1@example.com user1@dexample.com

  SigningTable: |
    *@rieau.cohesion-territoires.gouv.fr mail._domainkey.rieau.cohesion-territoires.gouv.fr

  KeyTable: |
    mail._domainkey.rieau.cohesion-territoires.gouv.fr rieau.cohesion-territoires.gouv.fr:mail:/etc/opendkim/keys/mail.private

  TrustedHosts: |
    127.0.0.1
    localhost
    94.23.208.200
    rieau.cohesion-territoires.gouv.fr