defaults: &defaults
  docker:
    - image: circleci/node:10.15.3-browsers
    - image: tristanrobert/rieau-ui
    - image: tristanrobert/rieau-api
    - image: tristanrobert/keycloak-france-connect
      environment: 
        KEYCLOAK_IMPORT: /tmp/rieau-dev.json
    - image: postgres:11-alpine
    - image: postgres:10-alpine
  working_directory: ~/project/rieau-infra

version: 2
jobs:
  e2e-tests:
    <<: *defaults
    steps:
      - run: git clone https://github.com/MTES-MCT/rieau-ui.git
      - attach_workspace:
          at: '~'
      - run: cp .env.sample .env
      - run: REACT_APP_API_MOCK=false npm run test:integration
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots 

  check-docker:
    docker:
      - image: knqyf263/trivy
    steps:
      - run:
          name: Scan the image vulnerabilities
          command: trivy --exit-code 0 --quiet --auto-refresh --clear-cache tristanrobert/rieau-ui:latest
      - run:
          name: Scan the image vulnerabilities
          command: trivy --exit-code 0 --quiet --auto-refresh --clear-cache tristanrobert/rieau-api:latest


workflows:
  version: 2
  weekly-check:
    triggers:
      - schedule:
          cron: "0 0 * * 0" # every sunday at midnight
          filters:
            branches:
              only:
                - master
    jobs:
      - check-docker:
          requires: []

  e2e-tests:
    jobs:
      - e2e-tests:
          requires: []
          filters:
            branches:
              only:
                - master
      - check-docker:
          requires: []
          filters:
            branches:
              only:
                - master

