defaults: &defaults
  docker:
    - image: knqyf263/trivy

version: 2
jobs:
  check-docker:
    <<: *defaults
    steps:
      - run:
          name: Scan the image vulnerabilities
          command: trivy --exit-code 0 --quiet --auto-refresh --clear-cache tristanrobert/rieau-ui:latest
      - run:
          name: Scan the image vulnerabilities
          command: trivy --exit-code 0 --quiet --auto-refresh --clear-cache tristanrobert/rieau-api:latest


workflows:
  version: 2
  weekly-check:
    triggers:
      - schedule:
          cron: "0 0 * * 0" # every sunday at midnight
          filters:
            branches:
              only:
                - master
    jobs:
      - check-docker:
          requires: []

  check-docker:
    jobs:
      - check-docker:
          requires: []
          filters:
            branches:
              only:
                - master

