version: '3'

networks:
  app:
  web:
    external: true
services:

  ui:
    image: tristanrobert/rieau-ui:0.2.0
    container_name: ui
    env_file: ./app.env
    depends_on:
      - api
    networks:
      - web
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ui"
      - "traefik.port=3000"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:rieau.cohesion-territoires.gouv.fr"
      - "traefik.frontend.headers.STSSeconds=31536000"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"

  api:
    image: tristanrobert/rieau-api
    env_file: ./app.env
    container_name: api
    volumes: 
      - ./application.properties:/app/config/application-staging.properties:ro
      - ./server.cer:/app/server.cer:ro
    depends_on:
      - db
      - files
    networks:
      - web
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=5000"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:rieau.cohesion-territoires.gouv.fr; PathPrefixStrip:/api"

  db:
    image: postgres:10-alpine
    networks:
      - app
    restart: unless-stopped
    env_file: ./app.env
    volumes:
      - /home/rieau/data/postgresql:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro

  files:
    image: minio/minio
    env_file: ./app.env
    networks:
      - app
    restart: unless-stopped
    command: server /data
    volumes:
      - /home/rieau/data/minio:/data

  demo:
    image: tristanrobert/rieau-ui:latest
    container_name: demo
    environment: 
      - SERVER_PORT=3100
      - REACT_APP_API_MOCK=true
      - REACT_APP_BASENAME=/demo
      - PUBLIC_URL=https://rieau.cohesion-territoires.gouv.fr/demo
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.backend=demo"
      - "traefik.port=3100"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:rieau.cohesion-territoires.gouv.fr; PathPrefixStrip:/demo"