version: '3'

networks:
  app:
  web:
    external: true
services:

  ui:
    image: tristanrobert/rieau-ui
    env_file: ./app.env
    depends_on:
      - api
    networks:
      - web
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=app"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:app.rieau.local"

  api:
    image: tristanrobert/rieau-api
    env_file: ./app.env
    depends_on:
      - db
      - files
    networks:
      - app

  db:
    image: postgres:10-alpine
    networks:
      - app
    restart: unless-stopped
    env_file: ./app.env
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro

  files:
    image: minio/minio
    env_file: ./app.env
    networks:
      - app
    restart: unless-stopped
    command: server /data