version: '3'

networks:
  app:
  web:
    external: true
services:

  ui:
    image: tristanrobert/rieau-ui
    container_name: ui
    env_file: ./app.env
    depends_on:
      - api
    networks:
      - web
      - app
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ui"
      - "traefik.port=3000"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:ui.docker.localhost"

  api:
    image: tristanrobert/rieau-api
    env_file: ./app.env
    container_name: api
    volumes: 
      - ./application.properties:/app/config/application-staging.properties:ro
    ports:
      - "5000:5000"
    depends_on:
      - db
      - files
    networks:
      - web
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=5000"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:api.docker.localhost"

  db:
    image: postgres:10-alpine
    networks:
      - app
    restart: unless-stopped
    env_file: ./app.env
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro

  files:
    image: minio/minio
    env_file: ./app.env
    networks:
      - app
    restart: unless-stopped
    command: server /data