version: '3'

services:
  vsftpd:
    image: fauria/vsftpd
    container_name: vsftpd
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes: 
      - "./test/data:/home/vsftpd"
    environment:
      FTP_USER: admin
      FTP_PASS: admin
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21100
    restart: always