FROM jboss/keycloak
LABEL maintainer="tristan.robert.44@gmail.com"
RUN curl -L https://github.com/InseeFr/Keycloak-FranceConnect/releases/download/1.1/keycloak-franceconnect-1.1.jar --output /opt/jboss/keycloak/standalone/deployments/keycloak-franceconnect-1.1.jar