version: '3.5'

networks:
  web:
    driver: bridge
    name: web

services:
  reverse-proxy:
    image: traefik:v1.7.12-alpine
    container_name: reverse-proxy
    environment:
      TZ: Europe/Paris
    ports:
      - "80:80"
      - "443:443"
      - "7000:7000"
    restart: unless-stopped
    volumes:
      - ./traefik.toml:/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/:/certs/:ro
    networks:
      web:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.docker.network=web"
      - "traefik.port=7000"
      - "traefik.frontend.rule=Host:reverse-proxy.docker.localhost"
      - "traefik.frontend.entryPoints=http,https" 