logLevel = "INFO"
defaultEntryPoints = ["http","https"]

[healthcheck]

[accessLog]

[retry]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]] # dev only
        certFile = "/certs/server.cer" # dev only
        keyFile = "/certs/server.key" # dev only
        insecureSkipVerify = true # dev only

[api]
dashboard=true
debug=false
entryPoint = "traefik"

[docker]
endpoint = "unix:///var/run/docker.sock"
exposedbydefault = false
domain = "docker.localhost"
watch = true
network = "web"

# [acme]
# email = "tristan.robert.44@gmail.com"
# storage = "acme.json"
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
# entryPoint = "https"
# onHostRule = true
#   [acme.httpChallenge]
#   entryPoint = "http"
# [[acme.domains]]
#  main = "rieau.cohesion-territoires.gouv.fr,*.rieau.cohesion-territoires.gouv.fr"
