---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-db-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi 
  storageClassName: local-storage