apiVersion: v1
kind: ConfigMap
metadata:
  name: config-app
data:
  application.properties: |
    # Profiles
    spring.profiles.active=default
    spring-boot.run.profiles=default

    #Dates
    app.date-format=dd/MM/yyyy
    app.year-format=yyyy
    app.datetime-format=dd/MM/yyyy HH:mm:ss
    app.all-datetime-format=[dd/MM/]yyyy[ HH:mm:ss]
    spring.jackson.date-format=${app.date-format}
    spring.jackson.time-zone=Europe/Paris

    # File upload
    spring.servlet.multipart.enabled=true
    spring.servlet.multipart.max-file-size=20MB
    spring.servlet.multipart.max-request-size=20MB

    #JMX
    spring.jmx.enabled=false

    #Logging
    logging.level.root = error
    logging.level.com.github.mtesmct.rieau = info

    # Persistence
    spring.jpa.open-in-view=false
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.url=jdbc:postgresql://localhost:5432/rieau
    spring.datasource.username=rieau
    spring.datasource.password=
    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
    spring.jpa.hibernate.ddl-auto=validate
    spring.jpa.generate-ddl=false
    spring.flyway.enabled=true
    spring.flyway.locations=classpath:db/migration/{vendor}

    #Security
    keycloak.enabled = true
    keycloak.principal-attribute=preferred_username
    keycloak.realm = rieau
    keycloak.auth-server-url = http://localhost:8080/auth
    keycloak.ssl-required = external
    keycloak.resource = rieau
    keycloak.use-resource-role-mappings = true
    app.cors-allowed-origins=http://localhost:3000

    # Fichiers
    minio.enabled = true
    minio.endpoint=http://localhost:9000
    minio.access-key=
    minio.secret-key=
    minio.bucket=rieau
    minio.buffer=4096

    # HTTP server
    server.port=5000
    
    # Communes
    app.communes-url=app.communes-url=https://geo.api.gouv.fr/communes?codePostal={codePostal}&fields=nom,code,codeDepartement,codeRegion&format=json&geometry=centre

    # Timeout en ms
    app.http-timeout=200

    # Proxy
    app.proxy-host=
    app.proxy-port=
    app.proxy-scheme=